version: '3.9'

services:
  auth:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 3091:3091
    depends_on:
      - auth-db
  
  auth-db:
    image: postgres:13
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=users
      - POSTGRES_USER=authdb
      - POSTGRES_PASSWORD=authdb-password

  auth-loadbalancer:
    build:
      context: ./loadbalancer/
      dockerfile: Dockerfile.dev
    ports:
      - 5100:5100
    depends_on:
      - auth
