# Build Stage
FROM gradle:7-jdk11-alpine AS builder

COPY --chown=gradle:gradle . /home/gradle/src

WORKDIR /home/gradle/src

RUN gradle build --no-daemon

# Run Stage
FROM openjdk:11-jre-slim

EXPOSE 3091

RUN mkdir /app

COPY --from=builder /home/gradle/src/build/libs/*.jar /app/auth-application.jar

ENTRYPOINT ["java", "-jar", "/app/auth-application.jar"]